### ISSUE TITLE
cudnn v5 support

### ISSUE THREAD

**Issue by vra** [pengxj/action-faster-rcnn#2]
Hi @pengxj ,
It seems that the cudnn v5 is not supported in this project, When I make with cudnn v5, it reports errors, while it's fine using cudnn v4. Could you please update the upstream of caffe to make it support cudnn v5? thanks.

**Comment by pengxj** [comment]
Hi @vra ,
Hmm. I guess you can simply clone the latest version of caffe. And then change the  python interface path in action_tools/__init__.py. If it's still the problem, let me know.

**Comment by vra** [comment]
Hi @pengxj ,
Thanks for your response, I will try it this way.

**Comment by pengxj** [comment]
My bad. You should clone the caffe tool from https://github.com/rbgirshick/py-faster-rcnn. The official caffe doesnot support ROI pooling.

**Comment by vra** [comment]
Okay got it

**Comment by vguptai** [comment]
@vra You can try this also. Hope this helps.

https://medium.com/@vikram.gupta/fixing-py-faster-rcnn-for-cudnn5-a7993d3ff3a1
